name: Generate Snake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонируем репо
      - uses: actions/checkout@v3

      # Генерация змейки
      - uses: Platane/snk@v3
        with:
          github_user_name: d3arkw
          outputs: github-contribution-grid-snake.svg

      # Пушим только если есть изменения
      - name: Commit and push Snake
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add github-contribution-grid-snake.svg
          # Только если есть изменения, коммитим
          git diff --cached --quiet || git commit -m "Update snake"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}